sudo: required

services:
  - docker

script:
  - make img

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - if [[ "$TRAVIS_BRANCH" == "master" ]];then make push-img; fi
  - if [[ "$TRAVIS_BRANCH" == "develop" ]];then make push-dev-img; fi
